platform :ios, '8.0'
#use_frameworks!

target 'TestTabelController' do
pod 'BlocksKit'
pod 'YYCache'
pod 'CocoaLumberjack'
pod 'libextobjc'
#pod 'ReactiveCocoa'
pod 'GYHttpMock'
pod 'GYDataCenter'
pod 'MLeaksFinder'
pod 'STAlertView'
pod 'evernote-cloud-sdk-ios'
pod 'AFNetworking'
pod 'OCMock'
pod 'Aspects'
# pod 'IQKeyboardManager', '~> 3.2.0.3'
 pod 'MJRefresh'
 pod 'MJExtension'
 pod 'pop'
 pod 'Masonry'
 pod 'SDAutoLayout'
end
